name: wechat_assets_picker_demo
description: The demo project for the wechat_assets_picker package.
version: 9.0.3+52
publish_to: none

environment:
  sdk: ^3.2.0
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  wechat_assets_picker:
    path: ../

  extended_image: ^8.2.0
  package_info_plus: '>=5.0.0 <7.0.0'
  path: ^1.8.0
  path_provider: ^2.0.15
  provider: ^6.0.2

  #  wechat_camera_picker: ^4.2.1
  wechat_camera_picker:
    git:
      url: git@github.com:LJWSW/flutter_wechat_camera_picker.git
      ref: flutter3.19/4.2.1

  photo_manager:
    git:
      url: git@github.com:LJWSW/flutter_photo_manager.git
      ref: flutter3.19/3.0.0

dev_dependencies:
  flutter_lints: any

flutter:
  uses-material-design: true
  assets:
    - assets/
